---
- name: Install and Configure Docker on EC2
  hosts: webserver
  become: yes
  gather_facts: no
  tasks:

    - name: Clean and Update all installed packages
      shell: sudo yum clean all && sudo yum -y update

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Add ec2-user to the docker group
      user:
        name: ec2-user
        groups: docker
        append: yes

    - name: Test Docker Installation
      command: docker --version
      register: docker_version

    - name: Show Docker Version
      debug:
        var: docker_version.stdout

    # Step 2: Build the Docker Image
    - name: Build Docker image for the app
      docker_image:
        path: /home/dhathri/deployNetwork/  # Change to the path containing your Dockerfile and app directory
        name: docker-flask-image          # Image name
        tag: latest                 # Tag for the image
        state: present              # Ensure image is built

    # Optional: Run the Docker container with your app
    - name: Run Docker container
      docker_container:
        name: flask-app-container
        image: docker-flask-image:latest
        state: started
        ports:
          - "8080:8080"  # Mapping ports (if your app runs on port 8080 inside the container)
        restart_policy: always
