---
- name: Install Docker, Configure, and Build Docker Image with App
  hosts: webserver  # Replace this with your target machine or group
  become: yes  # Use become to run tasks with sudo privileges
  tasks:

    # Step 1: Install Docker
    - name: Install required dependencies for Docker
      yum:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present
        update_cache: yes

    - name: Add Docker's official GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Set up the stable repository for Docker
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release | lower }} stable"
        state: present


    - name: Ensure Docker is started and enabled on boot
      service:
        name: docker
        state: started
        enabled: yes

    # Step 2: Build the Docker Image
    - name: Build Docker image for the app
      docker_image:
        path: /home/dhathri/deployNetwork  # Change to the path containing your Dockerfile and app directory
        name: docker-app-image          # Image name
        tag: latest                 # Tag for the image
        state: present              # Ensure image is built

    # Optional: Run the Docker container with your app
    - name: Run Docker container
      docker_container:
        name: docker-app-container
        image: docker-app-image:latest
        state: started
        ports:
          - "8080:8080"  # Mapping ports (if your app runs on port 8080 inside the container)
        restart_policy: always
